//
//  LSITipController.m
//  Tips
//
//  Created by Paul Solt on 5/12/20.
//  Copyright © 2020 Lambda School. All rights reserved.
//

// Import statements copy/paste code into this file
#import "LSITipController.h"
#import "LSITip.h"      // #3 Import header files in your .m files

// Class extension
@interface LSITipController () {
    // (Optional) Private instance variables
    //NSMutableArray *_tips;
}

// Private Properties
@property (nonatomic, readwrite) NSMutableArray<LSITip *> *internalTips;

// Private Outlets

// Private methods

@end


@implementation LSITipController

- (instancetype)init {
    self = [super init];
    if (self) {
        _internalTips = [[NSMutableArray alloc] init];
    }
    return self;
}

// Computed property (no autogenerated _instanceVariable)
- (NSArray<LSITip *> *)tips {
    // It's fast to return a copy in Objc/Swift
    return [_internalTips copy]; // copy: NSMutableArray -> NSArray (Copy on Write = COW)
}

- (void)addTip:(LSITip *)tip {
    [self.internalTips addObject:tip];
    
    // FUTURE: sync to firebase or CoreData
}

@end
