//
//  SABTipController.m
//  Tips
//
//  Created by Stephanie Ballard on 7/14/20.
//  Copyright © 2020 Lambda School. All rights reserved.
//

// Import statements copy and paste code into this file
#import "SABTipController.h"
#import "SABTip.h" // Import header files in your .m files

// Class extension
@interface SABTipController () {
    // (Optional) Private instance variables
    
}

// Private Properties
@property (nonatomic, readwrite) NSMutableArray<SABTip *> *internalTips;
// Private Outlets

// Private Methods

@end

@implementation SABTipController

- (instancetype)init {
    self = [super init];
    if (self) {
        _internalTips = [[NSMutableArray alloc] init];
    }
    return self;
}

// Computed property (no autogenerated _instanceVariable)
- (NSArray<SABTip *> *)tips {
    // It is fast to return a copy in Objc/Swift
    return [_internalTips copy]; // copy: NSMutableArray -> NSArray (Copy on Write = COW)
}

- (void)addTip:(SABTip *)tip {
    [self.internalTips addObject:tip];
    
    // Future: sync to firebase or CoreData
}

@end
